### ISSUE TITLE
pianonotes missing on filedropper

### ISSUE THREAD

**Issue by inder123** [ziad-halabi9/AlgorithmicMusicPlayer#1]
Is it possible for you to add the file to GitHub? If you can't add that, can you add another sample so that we can use it as a reference? Thanks.

**Comment by ziad-halabi9** [comment]
Check the updated link. Thanks!

**Comment by lomi17** [comment]
@inder123 have you ever try this project? Did it worked? Is yes can yousend a little help regarding on the generating the output .wav file? Thank you!

**Comment by inder123** [comment]
@lomi17 No, I didn't.
If you do end up using it, please share notes. Thanks.

**Comment by ziad-halabi9** [comment]
Thanks @lomi17 @inder123  for the feedback! I just pushed some changes. Try it out now and let me know how it goes!

**Comment by lomi17** [comment]
sorry for the late reply! it didn't pop up the notification on my gmail by
the way the code worked perfectly you can now use it and generate the sound
file

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_-5347364298581773726_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by lomi17** [comment]
@inder123 Sent my reply on gmail. By the way download now the upated project it will work perfectly big thanks to @ziad-halabi9

**Comment by inder123** [comment]
Thank you @lomi17  and @ziad-halabi9  Will check it out.
