### ISSUE TITLE
Not work in Android

### ISSUE THREAD

**Issue by zicohasan** [ziad-halabi9/AlgorithmicMusicPlayer#2]
Hai Zaid,
AlgorithmicMusicPlayer project isn't working in my AndroidStudio. When I run it, it did not produce the song.wav file nor playing any song. How I suppose to put the note path. I put the downloaded notes folder (pianonotes) in my root project. Then I change the path like below: 
       String path_piano_notes = "/pianonotes/";

**Comment by ziad-halabi9** [comment]
Hey zicohasan,

The example doesn't play the song, it simply produces a .wav file containing the output song. To debug it, try first printing all the files in your path_piano_notes to make sure the piano notes are in the right place. Then after running the `p.produce(path/file.wav)` you should find the wav file there. Make sure both paths do not have any space in them.
Thanks!

**Comment by slumcattt** [comment]
hi, I tried to compile your project and it gives me only a text view. my directory is fine.do I need to make some click listener or?

**Comment by ziad-halabi9** [comment]
The example provided only outputs a wav file of the piano melody. Nothing is shown on the screen. Thanks!

**Comment by lomi17** [comment]
Hi @ziad-halabi9, Ive been having a problem on your project. Even though the file path of the pianonotes is correct and also the path of the p.produce it doesn't create any .wav file. Please notice this and help me thank you and Godbless!

**Comment by lomi17** [comment]
Hey @zicohasan, did it worked? If yes can you send a little help? Cause mine didnt produce any .wav file although the file path is already correct. Thank you and Godbless!

**Comment by ziad-halabi9** [comment]
Thanks @lomi17 for the feedback! I just pushed some changes. Try it out now and let me know how it goes!

**Comment by lomi17** [comment]
@ziad-halabi9 Big thanks! I will try it today hope that it will produce the sound correctly. Ill letbyou inform right away!

**Comment by lomi17** [comment]
@ziad-halabi9, tried thr code already and for now it work properly! Big up for this! Tah k you very much and ill keep you updated about this project of yours thank you!

**Comment by lomi17** [comment]
Again Big thanks for the improvement of the code! it really generate the
musical notes/keys. By the way can i ask if what does the piano_left and
piano right_ stands for if you can compose all the keys in one
instruments?? Im expecting to have an answer asap thank you and God bless

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
